### ISSUE TITLE
add synteny detection

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/LIS-autocontent#3]
synteny in the datastore comes in two flavors. The one I'm more interested in at the moment is the one that shows off the major new features of JBrowse2 in this regard (e.g. dotplots, linked linear views). These will be represented by paf files and the bam files from which these were derived. The bam files can be handled as any other bam file, but the paf files require config that links them to both of the assemblies.

**Comment by DogPaws33** [comment]
Failed to get file, due to ambiguous naming of wanted files. Pairwise naming needs to be defined within README.yml

Example:
Real Link: https://data.legumeinfo.org/Arachis/hypogaea/synteny/Tifrunner.gnm2.0KEE/arahy.Tifrunner.gnm2.J5K5.x.aradu.V14167.gnm2.J7QH.minimap2.paf.gz

Generated Link: https://data.legumeinfo.org/Arachis/hypogaea/synteny/Tifrunner.gnm2.0KEE/arahy.Tifrunner.gnm2.0KEE.minimap2.paf.gz

Wildcard needed but cannot be accepted by http.

**Comment by adf-ncgr** [comment]
Not sure I am completely understanding the issue, but how is the autocontent generator figuring out that the path component Tifrunner.gnm2.0KEE exists and could the same mechanism be used to determine what files are present? If not, then maybe the thing to do is grab them from the CHECKSUM.<foldername>.md5 file, which we are supposed to generate for every datastore folder; I think that is more likely to be up to date with folder contents than trying to get people to update the README faithfully.

**Comment by ctcncgr** [comment]
This has been completed. Reopen if needed.
